export const data = JSON.parse("{\"key\":\"v-c6248a52\",\"path\":\"/fundamental/datastruct.html\",\"title\":\"数据结构思维导图\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"数据结构思维导图\",\"description\":\"This is the Data Structure mind map written down for the post-graduate examination. 这是备考研究生考试时写下的【数据结构】思维导图 ``` 版本：1.4.3 作者：zhiyu1998 ``` 特点：适用于考研、期末考大部分题型 我参考了多本书籍，写下的做题套路，希望能帮...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://zhiyu1998.github.io/fundamental/datastruct.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"数据结构思维导图\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"This is the Data Structure mind map written down for the post-graduate examination. 这是备考研究生考试时写下的【数据结构】思维导图 ``` 版本：1.4.3 作者：zhiyu1998 ``` 特点：适用于考研、期末考大部分题型 我参考了多本书籍，写下的做题套路，希望能帮...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://zhiyu1998.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"数据结构思维导图\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"zhiyu1998\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"数据结构思维导图\\\",\\\"image\\\":[\\\"https://zhiyu1998.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zhiyu1998\\\",\\\"url\\\":\\\"https://github.com/zhiyu1998\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"第一章   绪论\",\"slug\":\"第一章-绪论\",\"link\":\"#第一章-绪论\",\"children\":[]},{\"level\":3,\"title\":\"第二章  线性表\",\"slug\":\"第二章-线性表\",\"link\":\"#第二章-线性表\",\"children\":[]},{\"level\":3,\"title\":\"第三章  栈和队列\",\"slug\":\"第三章-栈和队列\",\"link\":\"#第三章-栈和队列\",\"children\":[]},{\"level\":3,\"title\":\"第三章 串\",\"slug\":\"第三章-串\",\"link\":\"#第三章-串\",\"children\":[]},{\"level\":3,\"title\":\"第四章  数组和广义表\",\"slug\":\"第四章-数组和广义表\",\"link\":\"#第四章-数组和广义表\",\"children\":[]},{\"level\":3,\"title\":\"第五章  树与二叉树\",\"slug\":\"第五章-树与二叉树\",\"link\":\"#第五章-树与二叉树\",\"children\":[]},{\"level\":3,\"title\":\"第六章  图\",\"slug\":\"第六章-图\",\"link\":\"#第六章-图\",\"children\":[]},{\"level\":3,\"title\":\"第七章 查找\",\"slug\":\"第七章-查找\",\"link\":\"#第七章-查找\",\"children\":[]},{\"level\":3,\"title\":\"第八章  排序\",\"slug\":\"第八章-排序\",\"link\":\"#第八章-排序\",\"children\":[]},{\"level\":3,\"title\":\"第九章  文件\",\"slug\":\"第九章-文件\",\"link\":\"#第九章-文件\",\"children\":[]},{\"level\":3,\"title\":\"考前必看题型\",\"slug\":\"考前必看题型\",\"link\":\"#考前必看题型\",\"children\":[]}],\"readingTime\":{\"minutes\":0.63,\"words\":188},\"filePathRelative\":\"fundamental/datastruct.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
