export const data = JSON.parse("{\"key\":\"v-43c99183\",\"path\":\"/Java/jvm/part1/4.%E7%A8%8B%E5%BA%8F%E8%AE%A1%E6%95%B0%E5%99%A8%EF%BC%88PC%E5%AF%84%E5%AD%98%E5%99%A8%EF%BC%89.html\",\"title\":\"程序计数器\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":4,\"title\":\"程序计数器\",\"category\":[\"JVM\"],\"tag\":[\"JVM上篇\"],\"description\":\"[TOC]\\r 官方文档网址：https://docs.oracle.com/javase/specs/jvms/se8/html/index.html (https://docs.oracle.com/javase/specs/jvms/se8/html/index.html) image 概述 每一个线程一份 定义 程序计数器是一块较小的内存空间，是...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://zhiyu1998.github.io/Java/jvm/part1/4.%E7%A8%8B%E5%BA%8F%E8%AE%A1%E6%95%B0%E5%99%A8%EF%BC%88PC%E5%AF%84%E5%AD%98%E5%99%A8%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"程序计数器\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[TOC]\\r 官方文档网址：https://docs.oracle.com/javase/specs/jvms/se8/html/index.html (https://docs.oracle.com/javase/specs/jvms/se8/html/index.html) image 概述 每一个线程一份 定义 程序计数器是一块较小的内存空间，是...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://zhiyu1998.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"程序计数器\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"zhiyu1998\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"JVM上篇\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"程序计数器\\\",\\\"image\\\":[\\\"https://zhiyu1998.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zhiyu1998\\\",\\\"url\\\":\\\"https://github.com/zhiyu1998\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"概述\",\"slug\":\"概述\",\"link\":\"#概述\",\"children\":[{\"level\":3,\"title\":\"定义\",\"slug\":\"定义\",\"link\":\"#定义\",\"children\":[]},{\"level\":3,\"title\":\"作用\",\"slug\":\"作用\",\"link\":\"#作用\",\"children\":[]},{\"level\":3,\"title\":\"特点\",\"slug\":\"特点\",\"link\":\"#特点\",\"children\":[]},{\"level\":3,\"title\":\"示例\",\"slug\":\"示例\",\"link\":\"#示例\",\"children\":[]}]},{\"level\":2,\"title\":\"两个常见的面试问题\",\"slug\":\"两个常见的面试问题\",\"link\":\"#两个常见的面试问题\",\"children\":[]},{\"level\":2,\"title\":\"CPU 时间片\",\"slug\":\"cpu-时间片\",\"link\":\"#cpu-时间片\",\"children\":[]}],\"readingTime\":{\"minutes\":4.1,\"words\":1230},\"filePathRelative\":\"Java/jvm/part1/4.程序计数器（PC寄存器）.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
