export const data = JSON.parse("{\"key\":\"v-347bb1b4\",\"path\":\"/Java/eightpart/distribution.html\",\"title\":\"分布式\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":8,\"author\":\"zhiyu1998\",\"title\":\"分布式\",\"description\":\"🔗 分布式 理论基础 CAP理论 CAP 理论/定理起源于 2000年，由加州大学伯克利分校的Eric Brewer教授在分布式计算原理研讨会（PODC）上提出，因此 CAP定理又被称作 布鲁尔定理（Brewer’s theorem） 2年后，麻省理工学院的Seth Gilbert和Nancy Lynch 发表了布鲁尔猜想的证明，CAP理论正式成为分...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://zhiyu1998.github.io/Java/eightpart/distribution.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"分布式\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🔗 分布式 理论基础 CAP理论 CAP 理论/定理起源于 2000年，由加州大学伯克利分校的Eric Brewer教授在分布式计算原理研讨会（PODC）上提出，因此 CAP定理又被称作 布鲁尔定理（Brewer’s theorem） 2年后，麻省理工学院的Seth Gilbert和Nancy Lynch 发表了布鲁尔猜想的证明，CAP理论正式成为分...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://zhiyu1998.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"分布式\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"zhiyu1998\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"分布式\\\",\\\"image\\\":[\\\"https://zhiyu1998.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zhiyu1998\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🔗 分布式\",\"slug\":\"🔗-分布式\",\"link\":\"#🔗-分布式\",\"children\":[{\"level\":3,\"title\":\"理论基础\",\"slug\":\"理论基础\",\"link\":\"#理论基础\",\"children\":[]},{\"level\":3,\"title\":\"了解RPC吗？\",\"slug\":\"了解rpc吗\",\"link\":\"#了解rpc吗\",\"children\":[]},{\"level\":3,\"title\":\"有哪些常见的 RPC 框架？\",\"slug\":\"有哪些常见的-rpc-框架\",\"link\":\"#有哪些常见的-rpc-框架\",\"children\":[]},{\"level\":3,\"title\":\"了解分布式事务吗？\",\"slug\":\"了解分布式事务吗\",\"link\":\"#了解分布式事务吗\",\"children\":[]},{\"level\":3,\"title\":\"常见保证幂等的方式\",\"slug\":\"常见保证幂等的方式\",\"link\":\"#常见保证幂等的方式\",\"children\":[]},{\"level\":3,\"title\":\"分布式系统接口，如何避免表单的重复提交？\",\"slug\":\"分布式系统接口-如何避免表单的重复提交\",\"link\":\"#分布式系统接口-如何避免表单的重复提交\",\"children\":[]},{\"level\":3,\"title\":\"有几种生成唯一ID的方式？\",\"slug\":\"有几种生成唯一id的方式\",\"link\":\"#有几种生成唯一id的方式\",\"children\":[]},{\"level\":3,\"title\":\"单点登录\",\"slug\":\"单点登录\",\"link\":\"#单点登录\",\"children\":[]},{\"level\":3,\"title\":\"Dubbo面试汇总\",\"slug\":\"dubbo面试汇总\",\"link\":\"#dubbo面试汇总\",\"children\":[]}]}],\"readingTime\":{\"minutes\":68.05,\"words\":20416},\"filePathRelative\":\"Java/eightpart/distribution.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
