export const data = JSON.parse("{\"key\":\"v-7d033bda\",\"path\":\"/Java/eightpart/intelligenceQuestion.html\",\"title\":\"智力题\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":14,\"author\":\"zhiyu1998\",\"title\":\"智力题\",\"description\":\"🙇‍♂️智力题 赛马找最快的马匹（高频题） 一般有这么几种问法： 25匹马5条跑道找最快的3匹马，需要跑几次？参考回答：7 64匹马8条跑道找最快的4匹马，需要跑几次？参考回答：11 25匹马5条跑道找最快的5匹马，需要跑几次？参考回答：最少8次最多9次 建议画图表来看，将问题简单化一点，将大问题化成小问题即可，同时B站有个讲解视频还不错：https...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://zhiyu1998.github.io/Java/eightpart/intelligenceQuestion.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"智力题\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🙇‍♂️智力题 赛马找最快的马匹（高频题） 一般有这么几种问法： 25匹马5条跑道找最快的3匹马，需要跑几次？参考回答：7 64匹马8条跑道找最快的4匹马，需要跑几次？参考回答：11 25匹马5条跑道找最快的5匹马，需要跑几次？参考回答：最少8次最多9次 建议画图表来看，将问题简单化一点，将大问题化成小问题即可，同时B站有个讲解视频还不错：https...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://zhiyu1998.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"智力题\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"zhiyu1998\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"智力题\\\",\\\"image\\\":[\\\"https://zhiyu1998.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zhiyu1998\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🙇‍♂️智力题\",\"slug\":\"🙇‍♂️智力题\",\"link\":\"#🙇‍♂️智力题\",\"children\":[{\"level\":3,\"title\":\"赛马找最快的马匹（高频题）\",\"slug\":\"赛马找最快的马匹-高频题\",\"link\":\"#赛马找最快的马匹-高频题\",\"children\":[]}]}],\"readingTime\":{\"minutes\":7.22,\"words\":2167},\"filePathRelative\":\"Java/eightpart/intelligenceQuestion.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
