export const data = JSON.parse("{\"key\":\"v-1a44c1ea\",\"path\":\"/Java/eightpart/spring.html\",\"title\":\"Spring系列\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":5,\"author\":\"zhiyu1998\",\"title\":\"Spring系列\",\"description\":\"🍃 Spring系列 ⭐️ spring中都有哪些设计模式？（2022热门问题） 1、简单工厂模式：BeanFactory就是简单工厂模式的体现，根据传入一个唯一标识来获得 Bean 对象。 ```java Override public Object getBean(String name) throws BeansException { asse...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://zhiyu1998.github.io/Java/eightpart/spring.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Spring系列\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🍃 Spring系列 ⭐️ spring中都有哪些设计模式？（2022热门问题） 1、简单工厂模式：BeanFactory就是简单工厂模式的体现，根据传入一个唯一标识来获得 Bean 对象。 ```java Override public Object getBean(String name) throws BeansException { asse...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://zhiyu1998.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Spring系列\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"zhiyu1998\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Spring系列\\\",\\\"image\\\":[\\\"https://zhiyu1998.github.io/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zhiyu1998\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🍃 Spring系列\",\"slug\":\"🍃-spring系列\",\"link\":\"#🍃-spring系列\",\"children\":[{\"level\":3,\"title\":\"⭐️ spring中都有哪些设计模式？（2022热门问题）\",\"slug\":\"⭐️-spring中都有哪些设计模式-2022热门问题\",\"link\":\"#⭐️-spring中都有哪些设计模式-2022热门问题\",\"children\":[]},{\"level\":3,\"title\":\"SpringBoot启动流程\",\"slug\":\"springboot启动流程\",\"link\":\"#springboot启动流程\",\"children\":[]},{\"level\":3,\"title\":\"Bean生命周期\",\"slug\":\"bean生命周期\",\"link\":\"#bean生命周期\",\"children\":[]},{\"level\":3,\"title\":\"@Autowired 和 @Resource 的区别是什么？\",\"slug\":\"autowired-和-resource-的区别是什么\",\"link\":\"#autowired-和-resource-的区别是什么\",\"children\":[]},{\"level\":3,\"title\":\"请描述Spring MVC的工作流程？描述一下 DispatcherServlet 的工作流程？\",\"slug\":\"请描述spring-mvc的工作流程-描述一下-dispatcherservlet-的工作流程\",\"link\":\"#请描述spring-mvc的工作流程-描述一下-dispatcherservlet-的工作流程\",\"children\":[]},{\"level\":3,\"title\":\"Spring中构造方法注入和设值注入有什么区别\",\"slug\":\"spring中构造方法注入和设值注入有什么区别\",\"link\":\"#spring中构造方法注入和设值注入有什么区别\",\"children\":[]},{\"level\":3,\"title\":\"⭐Spring怎么解决循环依赖的问题？\",\"slug\":\"spring怎么解决循环依赖的问题\",\"link\":\"#spring怎么解决循环依赖的问题\",\"children\":[]},{\"level\":3,\"title\":\"Transactional失效场景\",\"slug\":\"transactional失效场景\",\"link\":\"#transactional失效场景\",\"children\":[]}]}],\"readingTime\":{\"minutes\":25.14,\"words\":7543},\"filePathRelative\":\"Java/eightpart/spring.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
